### ISSUE TITLE
import_valkyria error (Blender 7.9)

### ISSUE THREAD

**Issue by Masamiki0218** [gomtuu/import_valkyria#12]
I'm trying to import Claude's model, but it just won't work. Here's what I get.
![error](https://user-images.githubusercontent.com/13398181/63231280-9c136b00-c219-11e9-918b-71dbee823929.png)
Even tho I'm trying to import Claude's model, this happens with literally every mlx file, so I can't import **ANY** model.
I don't understand what's happening. What should I do?

**Comment by gomtuu** [comment]
Have you installed `texconv` as outlined on the [wiki](https://github.com/gomtuu/import_valkyria/wiki/Valkyria-Chronicles-4-Textures)?

In short, just create a folder called `C:\Users\███\texconv`, then download `texconv.exe` from [this page](https://github.com/microsoft/DirectXTex/releases/tag/feb2019) and save it as `C:\Users\███\texconv\texconv.exe`. (Of course, replace ███ with your username.)

That should fix it, but let me know if it doesn't.

**Comment by Masamiki0218** [comment]
> Have you installed `texconv` as outlined on the [wiki](https://github.com/gomtuu/import_valkyria/wiki/Valkyria-Chronicles-4-Textures)?
> 
> In short, just create a folder called `C:\Users\███\texconv`, then download `texconv.exe` from [this page](https://github.com/microsoft/DirectXTex/releases/tag/feb2019) and save it as `C:\Users\███\texconv\texconv.exe`. (Of course, replace ███ with your username.)
> 
> That should fix it, but let me know if it doesn't.

Ok, this pretty much fixed it. My bad, I forgot to unzip and put the texconv.exe in my User folder.
