### ISSUE TITLE
Failed import models into blender

### ISSUE THREAD

**Issue by VladVanHells** [gomtuu/import_valkyria#14]
Hi!
I'm trying to import VC4 character models into blender but it always shows an error. But I remember that a few years ago everything imported just fine. Can you help?

Conditions:
1) VC4 (ver 1.03)
2) Blender (I've tried on a few ver.) - 2.67 / 2.74
3) Python 3.8
4) Plugin - import_valkyria 0.8

Message:
![error](https://user-images.githubusercontent.com/61380870/75112691-d3daef80-564e-11ea-8079-3c7bb0a61615.png)

**Comment by VladVanHells** [comment]
Sry! I should add a texture converter. My bad! Ty for awesome toolset!

**Comment by gomtuu** [comment]
Glad you figured it out! :)
